fix readme
biopet/fastqsync pull request #3
Opened 2017-10-27 11:48 UTC by DavyCats

### Description

_Give your PR a **concise** yet **descriptive** title_

----

### Checklist (never delete this)

- [ ] Each method/class/object/trait should have scaladocs
- [ ] Added methods are unit tested
- [ ] Test coverage may not drop
- [ ] Documentation should be updated if required

2017-10-30 12:05 UTC, ffinfo requested changes

2017-10-30 12:05 UTC, ffinfo commented on README.md
> +For documentation and manuals visit the [readthedocs page](http://biopet-FastqSync.readthedocs.io/en/latest/).
This link is not working

2017-10-30 12:14 UTC, DavyCats commented on README.md
> +For documentation and manuals visit the [readthedocs page](http://biopet-FastqSync.readthedocs.io/en/latest/).
These links don't work in any of them.

2017-11-02 09:53 UTC, ffinfo commented
Closing this because we going to use github pages anyway

2017-11-02 09:53 UTC, closed without merging